# Generated by Django 3.0.2 on 2021-02-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_proyecto', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre de Proyecto')),
                ('description', models.TextField(verbose_name='Descripcion del Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id_img', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name_pict', models.CharField(max_length=200, verbose_name='Nombre de Imagen')),
                ('url', models.CharField(max_length=500, verbose_name='Ruta de imagen')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.Project')),
            ],
        ),
    ]
