# Generated by Django 3.0.2 on 2021-02-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_auto_20210222_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
