# Generated by Django 3.0.2 on 2021-02-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_auto_20210222_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.ImageField(upload_to='../media/'),
        ),
    ]
