# Generated by Django 3.0.2 on 2021-02-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_auto_20210223_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture_head',
            field=models.ImageField(default='', upload_to='pictures/head'),
            preserve_default=False,
        ),
    ]
