# Generated by Django 3.0.2 on 2021-03-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0007_project_picture_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture_head',
            field=models.TextField(max_length=500, verbose_name='Imagen'),
        ),
    ]
