# Generated by Django 3.0.2 on 2021-03-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_auto_20210308_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('photo_profile', models.CharField(max_length=500, verbose_name='Imagen de perfil')),
                ('link_cv', models.CharField(max_length=500, verbose_name='Path CV')),
            ],
        ),
    ]
