# Generated by Django 3.0.2 on 2021-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0012_auto_20210322_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='link codigo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='link demo'),
        ),
    ]
